package dev.vex.client.world

import org.joml.Vector3f

data class Item(
    val id: Int,
    val name: String,
    val itemTextureIndex: Int // index in the items texture atlas
)

object Items {
    val AIR                                 = Item(,   ""                                     )

    val BRICK                               = Item(,  "Brick",                                )
    val STAINED_BRICK                       = Item(,  "Stained Brick",                        )

    // REFINED ORES AND GEMS

    val COAL                                = Item(,  "Coal"                                  )
    val COPPER_INGOT                        = Item(,  "Copper Ingot",                         )
    val TIN_INGOT                           = Item(,  "Tin Ingot",                            )
    val SILVER_INGOT                        = Item(,  "Silver Ingot",                         )
    val GOLD_INGOT                          = Item(,  "Gold Ingot",                           )
    val COBOLT_DUST                         = Item(,  "Cobolt Dust",                          )
    val LITHIUM_SALT                        = Item(,  "Lithium Salt",                         )
    val IRON_INGOT                          = Item(,  "Iron Ingot",                           )
    val STEEL_INGOT                         = Item(,  "Steel Ingot",                          )
    val BLUE_STEEL_INGOT                    = Item(,  "Blue Steel Ingot",                     )
    val PLATINUM_INGOT                      = Item(,  "Platinum Ingot",                       )
    val TITANIUM_INGOT                      = Item(,  "Titanium Ingot",                       )
    val MALACHITE_INGOT                     = Item(,  "Malachite Ingot",                      )
    val OPAL                                = Item(,  "Opal",                                 )
    val FIRE_OPAL                           = Item(,  "Fire Opal",                            )
    val MOONSTONE                           = Item(,  "Moonstone",                            )
    val SAPPHIRE                            = Item(,  "Sapphire",                             )
    val STAR_SAPPHIRE                       = Item(,  "Star Sapphire",                        )
    val RUBY                                = Item(,  "Ruby",                                 )
    val HEART_RUBY                          = Item(,  "Heart Ruby",                           )
    val AMETHYST                            = Item(,  "Amethyst",                             )
    val EMERALD                             = Item(,  "Emerald",                              )
    val DIAMOND                             = Item(,  "Diamond",                              )
    val BLACK_DIAMOND                       = Item(,  "Black Diamond",                        )
    val QUARTZ                              = Item(,  "Quartz",                               )
    val ROSE_QUARTZ                         = Item(,  "Rose Quartz",                          )
    val BLACK_QUARTZ                        = Item(,  "Black Quartz",                         )
    val ANTHRACITE                          = Item(,  "Anthracite",                           )
    val MAGNESITE                           = Item(,  "Magnesite",                            )
    val LUMINUM                             = Item(,  "Luminum",                              )

    // LIGHTS

    val TORCH                               = Item(,  "Torch",                                )
    val COBOLT_TORCH                        = Item(,  "Cobolt Torch",                         )
    val LUMINUM_TORCH                       = Item(,  "Luminum Torch",                        )
    val AMETHYST_TORCH                      = Item(,  "Amethyst Torch",                       )
    val UV_TORCH                            = Item(,  "Ultraviolet Torch",                    )

    // Doors

    val OAK_DOOR                            = Item(, "Oak Door",                              )
    val BIRCH_DOOR                          = Item(, "Birch Door",                            )
    val SPRUCE_DOOR                         = Item(, "Spruce Door",                           )
    val PINE_DOOR                           = Item(, "Pine Door",                             )
    val WILLOW_DOOR                         = Item(, "Willow Door",                           )
    val MAPLE_DOOR                          = Item(, "Maple Door",                            )
    val RUBBER_DOOR                         = Item(, "Rubber Door",                           )
    val LEMONWOOD_DOOR                      = Item(, "Lemonwood Door",                        )
    val LIMEWOOD_DOOR                       = Item(, "Limewood Door",                         )
    val APPLEWOOD_DOOR                      = Item(, "Applewood Door",                        )
    val CHERRY_DOOR                         = Item(, "Cherry Door",                           )
    val MANDARIN_DOOR                       = Item(, "Mandarin Door",                         )
    val BANANA_DOOR                         = Item(, "Banana Door",                           )
    val COPPER_DOOR                         = Item(, "Copper Door",                           )
    val TIN_DOOR                            = Item(, "Tin Door",                              )
    val SILVER_DOOR                         = Item(, "Silver Door",                           )
    val GOLD_DOOR                           = Item(, "Gold Door",                             )
    val IRON_DOOR                           = Item(, "Iron Door",                             )
    val PLATINUM_DOOR                       = Item(, "Platinum Door",                         )
    val TITANIUM_DOOR                       = Item(, "Titanium Door",                         )
    val MALACHITE_DOOR                      = Item(, "Malachite Door",                        )

    // Functional Utilities

    val LADDER                              = Item(,  "Ladder",                               )
    val ROPE                                = Item(,  "Rope",                                 )
    val WETSTONE                            = Item(,  "Wetstone",                             )

    // SAPLINGS

    val OAK_SAPLING                         = Item(,  "Oak Sapling",                          )
    val BIRCH_SAPLING                       = Item(,  "Birch Sapling",                        )
    val SPRUCE_SAPLING                      = Item(,  "Spruce Sapling",                       )
    val PINE_SAPLING                        = Item(,  "Pine Sapling",                         )
    val WILLOW_SAPLING                      = Item(,  "Willow Sapling",                       )
    val MAPLE_SAPLING                       = Item(,  "Maple Sapling",                        )
    val RUBBER_SAPLING                      = Item(,  "Rubber Sapling",                       )
    val LEMON_SAPLING                       = Item(,  "Lemon Sapling",                        )
    val LIME_SAPLING                        = Item(,  "Lime Sapling",                         )
    val APPLE_SAPLING                       = Item(,  "Apple Sapling",                        )
    val MANDARIN_SAPLING                    = Item(,  "Mandarin Sapling",                     )
    val BANANA_SAPLING                      = Item(,  "Banana Sapling",                       ) // nice
    val ESSENCE                             = Item(,  "Essence",                              )
    val TREE_SAP                            = Item(,  "Tree Sap",                             )
    val FEATHER                             = Item(,  "Feather",                              )

    // Foodstuffs

    val APPLE                               = Item(,  "Apple",                                )
    val CRYSTAL_APPLE                       = Item(,  "Crystal Apple",                        )
    val SWEETBERRY                          = Item(,  "Sweetberry",                           )
    val BLUEBERRY                           = Item(,  "Blueberry",                            )
    val BLACKBERRY                          = Item(,  "Blackberry",                           )
    val RASPBERRY                           = Item(,  "Raspberry"                             )
    val STRAWBERRY                          = Item(,  "Strawberry"                            )
    val CHERRY                              = Item(,  "Cherry"                                )
    val MANDARIN                            = Item(,  "Mandarin"                              )
    val LEMON                               = Item(,  "Lemon"                                 )
    val LIME                                = Item(,  "Lime"                                  )
    val WHEAT                               = Item(,  "Wheat",                                )
    val POTATO                              = Item(,  "Potato",                               )
    val CARROT                              = Item(,  "Carrot",                               )
    val CUCUMBER                            = Item(,  "Cucumber",                             )
    val COCOA                               = Item(,  "Cocoa",                                )
    val PUMPKIN_PIE                         = Item(,  "Pumpkin Pie",                          )
    val CHERRY_CHEESE_CAKE                  = Item(,  "Cherry Cake",                          )
    val STRAWBERRY_POUND_CAKE               = Item(,  "Stawberry Pound Cake",                 )
    val KEY_LIME_PIE                        = Item(,  "Key Lime Pie",                         )
    val BLUEBERRY_SHORTCAKE                 = Item(,  "Blueberry Pie",                        )
    val COCONUT_CAKE                        = Item(,  "Coconut Cake",                         )
    val SWEETBERRY_PIE                      = Item(,  "Sweetberry Pie",                       )
    val MANDARIN_CREAM_PIE                  = Item(,  "Mandarin Cream Pie",                   )
    val BANANA_CREAM_CHEESECAKE             = Item(,  "Banana Cream Cheesecake",              )
    val APPLE_PIE                           = Item(,  "Apple Pie",                            )
    val BLACKBERRY_PIE                      = Item(,  "Blackberry Pie",                       )
    val RASPBERRY_PIE                       = Item(,  "Raspberry Pie",                        )
    val RAZZLEBERRY_PIE                     = Item(,  "Razzleberry Pie",                      )
    val RAW_BEEF                            = Item(,  "Raw Beef",                             )
    val RAW_CHICKEN                         = Item(,  "Raw Chicken",                          )
    val RAW_MUTTON                          = Item(,  "Raw Mutton",                           )
    val RAW_PORK                            = Item(,  "Raw Pork",                             )
    val RAW_BACON                           = Item(,  "Raw Bacon",                            )
    val RAW_SAUSAGE                         = Item(,  "Raw Sausage",                          )
    val RAW_VENISON                         = Item(,  "Raw Venison",                          )
    val RAW_COD                             = Item(,  "Raw Cod",                              )
    val RAW_SALMON                          = Item(,  "Raw Salmon",                           )
    val RAW_TUNA                            = Item(,  "Raw Tuna",                             )
    val RAW_TROUT                           = Item(,  "Raw Trout",                            )
    val COOKED_BEEF                         = Item(,  "Steak",                                )
    val COOKED_CHICKEN                      = Item(,  "Cooked Chicken",                       )
    val COOKED_MUTTON                       = Item(,  "Cooked Mutton",                        )
    val COOKED_PORK                         = Item(,  "Cooked Porkchop",                      )
    val COOKED_BACON                        = Item(,  "Cooked Bacon",                         )
    val COOKED_SAUSAGE                      = Item(,  "Cooked Sausage",                       )
    val COOKED_VENISON                      = Item(,  "Cooked Venison",                       )
    val COOKED_COD                          = Item(,  "Cooked Cod",                           )
    val COOKED_SALMON                       = Item(,  "Cooked Salmon",                        )
    val COOKED_TUNA                         = Item(,  "Cooked Tuna",                          )
    val COOKED_TROUT                        = Item(,  "Cooked Trout",                         )
    val BREAD                               = Item(,  "Bread",                                )
    val TOAST                               = Item(,  "Toast",                                )
    val BUTTER                              = Item(,  "Butter",                               )
    val BUTTERED_TOAST                      = Item(,  "Buttered Toast",                       )
    val TOAST_WITH_KEY_LIME_JAM             = Item(,  "Toast with Key Lime Jam",              )
    val TOAST_WITH_SWEETBERRY_JAM           = Item(,  "Toast with Sweetberry Jam",            )
    val TOAST_WITH_APPLE_JAM                = Item(,  "Toast with Apple Jam",                 )
    val TOAST_WITH_BLACKBERRY_JAM           = Item(,  "Toast with Blackberry Jam",            )
    val TOAST_WITH_RASPBERRY_JAM            = Item(,  "Toast with Raspberry Jam",             )
    val TOAST_WITH_RAZZLEBERRY_JAM          = Item(,  "Toast with Razzleberry Jam",           )
    val TOAST_WITH_LEMON_JAM                = Item(,  "Toast with Lemon Jam",                 )
    val TOAST_WITH_BLUEBERRY_JAM            = Item(,  "Toast with Blueberry Jam",             )
    val BAGEL                               = Item(,  "Bagel",                                )
    val BAGEL_WITH_CREAM_CHEESE             = Item(,  "Bagel with Cream Cheese",              )
    val BAGEL_WITH_PUMPKIN_CREAM_CHEESE     = Item(,  "Bagel with Pumpkin Cream Cheese",      )
    val BAGEL_WITH_STRAWBERRY_CREAM_CHEESE  = Item(,  "Bagel with Strawberry Cream Cheese",   )
    val BAGEL_WITH_BLUEBERRY_CREAM_CHEESE   = Item(,  "Bagel with Blueberry Cream Cheese",    )
    val BAGEL_WITH_SWEETBERRY_CREAM_CHEESE  = Item(,  "Bagel with Sweetberry Cream Cheese",   )
    val BAGEL_WITH_RAZZLEBERRY_CREAM_CHEESE = Item(,  "Bagel with Razzleberry Cream Cheese",  )
    val OLIVE                               = Item(,  "Olive",                                )
    val OLIVE_OIL                           = Item(,  "Olive Oil",                            )
    val LIGHTER                             = Item(,  "Lighter",                              )
    val BUCKET                              = Item(,  "Bucket",                               )
    val WATER_BUCKET                        = Item(,  "Water Bucket",                         )
    val LAVA_BUCKET                         = Item(,  "Lava Bucket",                          )
    val CHICKEN_EGG                         = Item(,  "Chicken Egg",                          )
    val DUCK_EGG                            = Item(,  "Duck Egg",                             )
    val FRIED_EGG                           = Item(,  "Fried Egg",                            )

    // ARMORS, WEAPONS, AND TOOLS

    val LEATHER                             = Item(, "", )
    val LEATHER_CAP                         = Item(, "", )
    val LEATHER_SHIRT                       = Item(, "", )
    val LEATHER_JACKET                      = Item(, "", )
    val LEATHER_TROUSERS                    = Item(, "", )
    val LEATHER_SHOES                       = Item(, "", )
    val LEATHER_GLOVES                      = Item(, "", )
    val WOODEN_DAGGER                       = Item(, "", )
    val WOODEN_SWORD                        = Item(, "", )
    val WOODEN_LONGSWORD                    = Item(, "", )
    val WOODEN_GREATSWORD                   = Item(, "", )
    val WOODEN_AXE                          = Item(, "", )
    val WOODEN_BATTLEAXE                    = Item(, "", )
    val WOODEN_PICKAXE                      = Item(, "", )
    val WOODEN_ICEPICK                      = Item(, "", )
    val WOODEN_SPADE                        = Item(, "", )
    val WOODEN_SPEAR                        = Item(, "", )
    val WOODEN_HOE                          = Item(, "", )
    val WOODEN_SYTHE                        = Item(, "", )

    val COPPER_HELMET                       = Item(, "", )
    val COPPER_CHAINMAIL                    = Item(, "", )
    val COPPER_BREASTPLATE                  = Item(, "", )
    val COPPER_GAUNTLETS                    = Item(, "", )
    val COPPER_GRIEVES                      = Item(, "", )
    val COPPER_BOOTS                        = Item(, "", )
    val COPPER_DAGGER                       = Item(, "", )
    val COPPER_SWORD                        = Item(, "", )
    val COPPER_LONGSWORD                    = Item(, "", )
    val COPPER_GREATSWORD                   = Item(, "", )
    val COPPER_AXE                          = Item(, "", )
    val COPPER_BATTLEAXE                    = Item(, "", )
    val COPPER_PICKAXE                      = Item(, "", )
    val COPPER_ICEPICK                      = Item(, "", )
    val COPPER_SPADE                        = Item(, "", )
    val COPPER_SPEAR                        = Item(, "", )
    val COPPER_HOE                          = Item(, "", )
    val COPPER_SYTHE                        = Item(, "", )

    val TIN_HELMET                          = Item(, "", )
    val TIN_CHAINMAIL                       = Item(, "", )
    val TIN_BREASTPLATE                     = Item(, "", )
    val TIN_GAUNTLETS                       = Item(, "", )
    val TIN_GRIEVES                         = Item(, "", )
    val TIN_BOOTS                           = Item(, "", )
    val TIN_DAGGER                          = Item(, "", )
    val TIN_SWORD                           = Item(, "", )
    val TIN_LONGSWORD                       = Item(, "", )
    val TIN_GREATSWORD                      = Item(, "", )
    val TIN_AXE                             = Item(, "", )
    val TIN_BATTLEAXE                       = Item(, "", )
    val TIN_PICKAXE                         = Item(, "", )
    val TIN_ICEPICK                         = Item(, "", )
    val TIN_SPADE                           = Item(, "", )
    val TIN_SPEAR                           = Item(, "", )
    val TIN_HOE                             = Item(, "", )
    val TIN_SYTHE                           = Item(, "", )

    val SILVER_HELMET                       = Item(, "", )
    val SILVER_CHAINMAIL                    = Item(, "", )
    val SILVER_BREASTPLATE                  = Item(, "", )
    val SILVER_GAUNTLETS                    = Item(, "", )
    val SILVER_GRIEVES                      = Item(, "", )
    val SILVER_BOOTS                        = Item(, "", )
    val SILVER_DAGGER                       = Item(, "", )
    val SILVER_SWORD                        = Item(, "", )
    val SILVER_LONGSWORD                    = Item(, "", )
    val SILVER_GREATSWORD                   = Item(, "", )
    val SILVER_AXE                          = Item(, "", )
    val SILVER_BATTLEAXE                    = Item(, "", )
    val SILVER_PICKAXE                      = Item(, "", )
    val SILVER_ICEPICK                      = Item(, "", )
    val SILVER_SPADE                        = Item(, "", )
    val SILVER_SPEAR                        = Item(, "", )
    val SILVER_HOE                          = Item(, "", )
    val SILVER_SYTHE                        = Item(, "", )

    val GOLD_HELMET                         = Item(, "", )
    val GOLD_CHAINMAIL                      = Item(, "", )
    val GOLD_BREASTPLATE                    = Item(, "", )
    val GOLD_GAUNTLETS                      = Item(, "", )
    val GOLD_GRIEVES                        = Item(, "", )
    val GOLD_BOOTS                          = Item(, "", )
    val GOLD_DAGGER                         = Item(, "", )
    val GOLD_SWORD                          = Item(, "", )
    val GOLD_LONGSWORD                      = Item(, "", )
    val GOLD_GREATSWORD                     = Item(, "", )
    val GOLD_AXE                            = Item(, "", )
    val GOLD_BATTLEAXE                      = Item(, "", )
    val GOLD_PICKAXE                        = Item(, "", )
    val GOLD_ICEPICK                        = Item(, "", )
    val GOLD_SPADE                          = Item(, "", )
    val GOLD_SPEAR                          = Item(, "", )
    val GOLD_HOE                            = Item(, "", )
    val GOLD_SYTHE                          = Item(, "", )

    val COBOLT_HELMET                       = Item(, "", )
    val COBOLT_CHAINMAIL                    = Item(, "", )
    val COBOLT_BREASTPLATE                  = Item(, "", )
    val COBOLT_GAUNTLETS                    = Item(, "", )
    val COBOLT_GRIEVES                      = Item(, "", )
    val COBOLT_BOOTS                        = Item(, "", )
    val COBOLT_DAGGER                       = Item(, "", )
    val COBOLT_SWORD                        = Item(, "", )
    val COBOLT_LONGSWORD                    = Item(, "", )
    val COBOLT_GREATSWORD                   = Item(, "", )
    val COBOLT_AXE                          = Item(, "", )
    val COBOLT_BATTLEAXE                    = Item(, "", )
    val COBOLT_PICKAXE                      = Item(, "", )
    val COBOLT_ICEPICK                      = Item(, "", )
    val COBOLT_SPADE                        = Item(, "", )
    val COBOLT_SPEAR                        = Item(, "", )
    val COBOLT_HOE                          = Item(, "", )
    val COBOLT_SYTHE                        = Item(, "", )

    val LITHIUM_HELMET                      = Item(, "", )
    val LITHIUM_CHAINMAIL                   = Item(, "", )
    val LITHIUM_BREASTPLATE                 = Item(, "", )
    val LITHIUM_GAUNTLETS                   = Item(, "", )
    val LITHIUM_GRIEVES                     = Item(, "", )
    val LITHIUM_BOOTS                       = Item(, "", )
    val LITHIUM_DAGGER                      = Item(, "", )
    val LITHIUM_SWORD                       = Item(, "", )
    val LITHIUM_LONGSWORD                   = Item(, "", )
    val LITHIUM_GREATSWORD                  = Item(, "", )
    val LITHIUM_AXE                         = Item(, "", )
    val LITHIUM_BATTLEAXE                   = Item(, "", )
    val LITHIUM_PICKAXE                     = Item(, "", )
    val LITHIUM_ICEPICK                     = Item(, "", )
    val LITHIUM_SPADE                       = Item(, "", )
    val LITHIUM_SPEAR                       = Item(, "", )
    val LITHIUM_HOE                         = Item(, "", )
    val LITHIUM_SYTHE                       = Item(, "", )

    val IRON_HELMET                         = Item(, "", )
    val IRON_CHAINMAIL                      = Item(, "", )
    val IRON_BREASTPLATE                    = Item(, "", )
    val IRON_GAUNTLETS                      = Item(, "", )
    val IRON_GRIEVES                        = Item(, "", )
    val IRON_BOOTS                          = Item(, "", )
    val IRON_DAGGER                         = Item(, "", )
    val IRON_SWORD                          = Item(, "", )
    val IRON_LONGSWORD                      = Item(, "", )
    val IRON_GREATSWORD                     = Item(, "", )
    val IRON_AXE                            = Item(, "", )
    val IRON_BATTLEAXE                      = Item(, "", )
    val IRON_PICKAXE                        = Item(, "", )
    val IRON_ICEPICK                        = Item(, "", )
    val IRON_SPADE                          = Item(, "", )
    val IRON_SPEAR                          = Item(, "", )
    val IRON_HOE                            = Item(, "", )
    val IRON_SYTHE                          = Item(, "", )

    val STEEL_HELMET                        = Item(, "", )
    val STEEL_CHAINMAIL                     = Item(, "", )
    val STEEL_BREASTPLATE                   = Item(, "", )
    val STEEL_GAUNTLETS                     = Item(, "", )
    val STEEL_GRIEVES                       = Item(, "", )
    val STEEL_BOOTS                         = Item(, "", )
    val STEEL_DAGGER                        = Item(, "", )
    val STEEL_SWORD                         = Item(, "", )
    val STEEL_LONGSWORD                     = Item(, "", )
    val STEEL_GREATSWORD                    = Item(, "", )
    val STEEL_AXE                           = Item(, "", )
    val STEEL_BATTLEAXE                     = Item(, "", )
    val STEEL_PICKAXE                       = Item(, "", )
    val BLUE_STEEL_ICEPICK                  = Item(, "", )
    val STEEL_SPADE                         = Item(, "", )
    val STEEL_SPEAR                         = Item(, "", )
    val STEEL_HOE                           = Item(, "", )
    val STEEL_SYTHE                         = Item(, "", )

    val BLUE_STEEL_HELMET                   = Item(, "", )
    val BLUE_STEEL_CHAINMAIL                = Item(, "", )
    val BLUE_STEEL_BREASTPLA                = Item(, "", )
    val BLUE_STEEL_GAUNTLETS                = Item(, "", )
    val BLUE_STEEL_GRIEVES                  = Item(, "", )
    val BLUE_STEEL_BOOTS                    = Item(, "", )
    val BLUE_STEEL_DAGGER                   = Item(, "", )
    val BLUE_STEEL_SWORD                    = Item(, "", )
    val BLUE_STEEL_LONGSWORD                = Item(, "", )
    val BLUE_STEEL_GREATSWOR                = Item(, "", )
    val BLUE_STEEL_AXE                      = Item(, "", )
    val BLUE_STEEL_BATTLEAXE                = Item(, "", )
    val BLUE_STEEL_PICKAXE                  = Item(, "", )
    val BLUE_STEEL_ICEPICK                  = Item(, "", )
    val BLUE_STEEL_SPADE                    = Item(, "", )
    val BLUE_STEEL_SPEAR                    = Item(, "", )
    val BLUE_STEEL_HOE                      = Item(, "", )
    val BLUE_STEEL_SYTHE                    = Item(, "", )

    val PLATINUM_HELMET                     = Item(, "", )
    val PLATINUM_CHAINMAIL                  = Item(, "", )
    val PLATINUM_BREASTPLATE                = Item(, "", )
    val PLATINUM_GAUNTLETS                  = Item(, "", )
    val PLATINUM_GRIEVES                    = Item(, "", )
    val PLATINUM_BOOTS                      = Item(, "", )
    val PLATINUM_DAGGER                     = Item(, "", )
    val PLATINUM_SWORD                      = Item(, "", )
    val PLATINUM_LONGSWORD                  = Item(, "", )
    val PLATINUM_GREATSWORD                 = Item(, "", )
    val PLATINUM_AXE                        = Item(, "", )
    val PLATINUM_BATTLEAXE                  = Item(, "", )
    val PLATINUM_PICKAXE                    = Item(, "", )
    val PLATINUM_ICEPICK                    = Item(, "", )
    val PLATINUM_SPADE                      = Item(, "", )
    val PLATINUM_SPEAR                      = Item(, "", )
    val PLATINUM_HOE                        = Item(, "", )
    val PLATINUM_SYTHE                      = Item(, "", )

    val TITANIUM_HELMET                     = Item(, "", )
    val TITANIUM_BREASTPLATE                = Item(, "", )
    val TITANIUM_CHAINMAIL                  = Item(, "", )
    val TITANIUM_GAUNTLETS                  = Item(, "", )
    val TITANIUM_GRIEVES                    = Item(, "", )
    val TITANIUM_BOOTS                      = Item(, "", )
    val TITANIUM_DAGGER                     = Item(, "", )
    val TITANIUM_SWORD                      = Item(, "", )
    val TITANIUM_LONGSWORD                  = Item(, "", )
    val TITANIUM_GREATSWORD                 = Item(, "", )
    val TITANIUM_AXE                        = Item(, "", )
    val TITANIUM_BATTLEAXE                  = Item(, "", )
    val TITANIUM_PICKAXE                    = Item(, "", )
    val MALACHITE_ICEPICK                   = Item(, "", )
    val TITANIUM_SPADE                      = Item(, "", )
    val TITANIUM_SPEAR                      = Item(, "", )
    val TITANIUM_HOE                        = Item(, "", )
    val TITANIUM_SYTHE                      = Item(, "", )

    val MALACHITE_HELMET                    = Item(, "", )
    val MALACHITE_BREASTPLATE               = Item(, "", )
    val MALACHITE_CHAINMAIL                 = Item(, "", )
    val MALACHITE_GAUNTLETS                 = Item(, "", )
    val MALACHITE_GRIEVES                   = Item(, "", )
    val MALACHITE_BOOTS                     = Item(, "", )
    val MALACHITE_DAGGER                    = Item(, "", )
    val MALACHITE_SWORD                     = Item(, "", )
    val MALACHITE_LONGSWORD                 = Item(, "", )
    val MALACHITE_GREATSWORD                = Item(, "", )
    val MALACHITE_AXE                       = Item(, "", )
    val MALACHITE_BATTLEAXE                 = Item(, "", )
    val MALACHITE_PICKAXE                   = Item(, "", )
    val MALACHITE_ICEPICK                   = Item(, "", )
    val MALACHITE_SPADE                     = Item(, "", )
    val MALACHITE_SPEAR                     = Item(, "", )
    val MALACHITE_HOE                       = Item(, "", )
    val MALACHITE_SYTHE                     = Item(, "", )
}