package dev.vex.client.world

import org.joml.Vector3f

data class Item(
    val id: Int,
    val name: String,
    val itemTextureIndex: Int // index in the items texture atlas
)

object Items {
    val AIR                                 = Item(0,   "",                                     0)

    val BRICK                               = Item(1,  "Brick",                                 1)
    val STAINED_BRICK                       = Item(2,  "Stained Brick",                         2)

    // REFINED ORES AND GEMS

    val COAL                                = Item(3,  "Coal",                                  3)
    val COPPER_INGOT                        = Item(4,  "Copper Ingot",                          4)
    val TIN_INGOT                           = Item(5,  "Tin Ingot",                             5)
    val SILVER_INGOT                        = Item(6,  "Silver Ingot",                          6)
    val GOLD_INGOT                          = Item(7,  "Gold Ingot",                            7)
    val COBOLT_DUST                         = Item(8,  "Cobolt Dust",                           8)
    val LITHIUM_SALT                        = Item(9,  "Lithium Salt",                          9)
    val IRON_INGOT                          = Item(10,  "Iron Ingot",                           10)
    val STEEL_INGOT                         = Item(11,  "Steel Ingot",                          11)
    val BLUE_STEEL_INGOT                    = Item(12,  "Blue Steel Ingot",                     12)
    val PLATINUM_INGOT                      = Item(13,  "Platinum Ingot",                       13)
    val TITANIUM_INGOT                      = Item(14,  "Titanium Ingot",                       14)
    val MALACHITE_INGOT                     = Item(15,  "Malachite Ingot",                      15)
    val OPAL                                = Item(16,  "Opal",                                 16)
    val FIRE_OPAL                           = Item(17,  "Fire Opal",                            17)
    val MOONSTONE                           = Item(18,  "Moonstone",                            18)
    val SAPPHIRE                            = Item(19,  "Sapphire",                             19)
    val STAR_SAPPHIRE                       = Item(20,  "Star Sapphire",                        20)
    val RUBY                                = Item(21,  "Ruby",                                 21)
    val HEART_RUBY                          = Item(22,  "Heart Ruby",                           22)
    val AMETHYST                            = Item(23,  "Amethyst",                             23)
    val EMERALD                             = Item(24,  "Emerald",                              24)
    val DIAMOND                             = Item(25,  "Diamond",                              25)
    val BLACK_DIAMOND                       = Item(26,  "Black Diamond",                        26)
    val QUARTZ                              = Item(27,  "Quartz",                               27)
    val ROSE_QUARTZ                         = Item(28,  "Rose Quartz",                          28)
    val BLACK_QUARTZ                        = Item(29,  "Black Quartz",                         29)
    val ANTHRACITE                          = Item(30,  "Anthracite",                           30)
    val MAGNESITE                           = Item(31,  "Magnesite",                            31)
    val LUMINUM                             = Item(32,  "Luminum",                              32)

    // LIGHTS

    val TORCH                               = Item(33,  "Torch",                                33)
    val COBOLT_TORCH                        = Item(34,  "Cobolt Torch",                         34)
    val LUMINUM_TORCH                       = Item(35,  "Luminum Torch",                        35)
    val AMETHYST_TORCH                      = Item(36,  "Amethyst Torch",                       36)
    val UV_TORCH                            = Item(37,  "Ultraviolet Torch",                    37)

    // Doors

    val OAK_DOOR                            = Item(38, "Oak Door",                              38)
    val BIRCH_DOOR                          = Item(39, "Birch Door",                            39)
    val SPRUCE_DOOR                         = Item(40, "Spruce Door",                           40)
    val PINE_DOOR                           = Item(41, "Pine Door",                             41)
    val WILLOW_DOOR                         = Item(42, "Willow Door",                           42)
    val MAPLE_DOOR                          = Item(43, "Maple Door",                            43)
    val RUBBER_DOOR                         = Item(44, "Rubber Door",                           44)
    val LEMONWOOD_DOOR                      = Item(45, "Lemonwood Door",                        45)
    val LIMEWOOD_DOOR                       = Item(46, "Limewood Door",                         46)
    val APPLEWOOD_DOOR                      = Item(47, "Applewood Door",                        47)
    val CHERRY_DOOR                         = Item(48, "Cherry Door",                           48)
    val MANDARIN_DOOR                       = Item(49, "Mandarin Door",                         49)
    val BANANA_DOOR                         = Item(50, "Banana Door",                           50)
    val COPPER_DOOR                         = Item(51, "Copper Door",                           51)
    val TIN_DOOR                            = Item(52, "Tin Door",                              52)
    val SILVER_DOOR                         = Item(53, "Silver Door",                           53)
    val GOLD_DOOR                           = Item(54, "Gold Door",                             54)
    val IRON_DOOR                           = Item(55, "Iron Door",                             55)
    val PLATINUM_DOOR                       = Item(56, "Platinum Door",                         56)
    val TITANIUM_DOOR                       = Item(57, "Titanium Door",                         57)
    val MALACHITE_DOOR                      = Item(58, "Malachite Door",                        58)

    // Functional Utilities

    val LADDER                              = Item(59,  "Ladder",                               59)
    val ROPE                                = Item(60,  "Rope",                                 60)
    val WETSTONE                            = Item(61,  "Wetstone",                             61)

    // SAPLINGS

    val OAK_SAPLING                         = Item(62,  "Oak Sapling",                          62)
    val BIRCH_SAPLING                       = Item(63,  "Birch Sapling",                        63)
    val SPRUCE_SAPLING                      = Item(64,  "Spruce Sapling",                       64)
    val PINE_SAPLING                        = Item(65,  "Pine Sapling",                         65)
    val WILLOW_SAPLING                      = Item(66,  "Willow Sapling",                       66)
    val MAPLE_SAPLING                       = Item(67,  "Maple Sapling",                        67)
    val RUBBER_SAPLING                      = Item(68,  "Rubber Sapling",                       68)
    val LEMON_SAPLING                       = Item(69,  "Lemon Sapling",                        69)
    val LIME_SAPLING                        = Item(70,  "Lime Sapling",                         70)
    val APPLE_SAPLING                       = Item(71,  "Apple Sapling",                        71)
    val MANDARIN_SAPLING                    = Item(72,  "Mandarin Sapling",                     72)
    val BANANA_SAPLING                      = Item(73,  "Banana Sapling",                       73) // nice
    val ESSENCE                             = Item(74,  "Essence",                              74)
    val TREE_SAP                            = Item(75,  "Tree Sap",                             75)
    val FEATHER                             = Item(76,  "Feather",                              76)

    // Foodstuffs

    val APPLE                               = Item(77,  "Apple",                                77)
    val CRYSTAL_APPLE                       = Item(78,  "Crystal Apple",                        78)
    val SWEETBERRY                          = Item(79,  "Sweetberry",                           79)
    val BLUEBERRY                           = Item(80,  "Blueberry",                            80)
    val BLACKBERRY                          = Item(81,  "Blackberry",                           81)
    val RASPBERRY                           = Item(82,  "Raspberry",                            82)
    val STRAWBERRY                          = Item(83,  "Strawberry",                           83)
    val CHERRY                              = Item(84,  "Cherry",                               84)
    val MANDARIN                            = Item(85,  "Mandarin",                             85)
    val LEMON                               = Item(86,  "Lemon",                                86)
    val LIME                                = Item(87,  "Lime",                                 87)
    val WHEAT                               = Item(88,  "Wheat",                                88)
    val POTATO                              = Item(89,  "Potato",                               89)
    val CARROT                              = Item(90,  "Carrot",                               90)
    val CUCUMBER                            = Item(91,  "Cucumber",                             91)
    val COCOA                               = Item(92,  "Cocoa",                                92)
    val PUMPKIN_PIE                         = Item(93,  "Pumpkin Pie",                          93)
    val CHERRY_CHEESE_CAKE                  = Item(94,  "Cherry Cake",                          94)
    val STRAWBERRY_POUND_CAKE               = Item(95,  "Stawberry Pound Cake",                 95)
    val KEY_LIME_PIE                        = Item(96,  "Key Lime Pie",                         96)
    val BLUEBERRY_SHORTCAKE                 = Item(97,  "Blueberry Pie",                        97)
    val COCONUT_CAKE                        = Item(98,  "Coconut Cake",                         98)
    val SWEETBERRY_PIE                      = Item(99,  "Sweetberry Pie",                       99)
    val MANDARIN_CREAM_PIE                  = Item(100,  "Mandarin Cream Pie",                  100)
    val BANANA_CREAM_CHEESECAKE             = Item(101,  "Banana Cream Cheesecake",             101)
    val APPLE_PIE                           = Item(102,  "Apple Pie",                           102)
    val BLACKBERRY_PIE                      = Item(103,  "Blackberry Pie",                      103)
    val RASPBERRY_PIE                       = Item(104,  "Raspberry Pie",                       104)
    val RAZZLEBERRY_PIE                     = Item(105,  "Razzleberry Pie",                     105)
    val RAW_BEEF                            = Item(106,  "Raw Beef",                            106)
    val RAW_CHICKEN                         = Item(107,  "Raw Chicken",                         107)
    val RAW_MUTTON                          = Item(108,  "Raw Mutton",                          108)
    val RAW_PORK                            = Item(109,  "Raw Pork",                            109)
    val RAW_BACON                           = Item(110,  "Raw Bacon",                           110)
    val RAW_SAUSAGE                         = Item(111,  "Raw Sausage",                         111)
    val RAW_VENISON                         = Item(112,  "Raw Venison",                         112)
    val RAW_COD                             = Item(113,  "Raw Cod",                             113)
    val RAW_SALMON                          = Item(114,  "Raw Salmon",                          114)
    val RAW_TUNA                            = Item(115,  "Raw Tuna",                            115)
    val RAW_TROUT                           = Item(116,  "Raw Trout",                           116)
    val COOKED_BEEF                         = Item(117,  "Steak",                               117)
    val COOKED_CHICKEN                      = Item(118,  "Cooked Chicken",                      118)
    val COOKED_MUTTON                       = Item(119,  "Cooked Mutton",                       119)
    val COOKED_PORK                         = Item(120,  "Cooked Porkchop",                     120)
    val COOKED_BACON                        = Item(121,  "Cooked Bacon",                        121)
    val COOKED_SAUSAGE                      = Item(122,  "Cooked Sausage",                      122)
    val COOKED_VENISON                      = Item(123,  "Cooked Venison",                      123)
    val COOKED_COD                          = Item(124,  "Cooked Cod",                          124)
    val COOKED_SALMON                       = Item(125,  "Cooked Salmon",                       125)
    val COOKED_TUNA                         = Item(126,  "Cooked Tuna",                         126)
    val COOKED_TROUT                        = Item(127,  "Cooked Trout",                        127)
    val BREAD                               = Item(128,  "Bread",                               128)
    val TOAST                               = Item(129,  "Toast",                               129)
    val BUTTER                              = Item(130,  "Butter",                              130)
    val BUTTERED_TOAST                      = Item(131,  "Buttered Toast",                      131)
    val TOAST_WITH_KEY_LIME_JAM             = Item(132,  "Toast with Key Lime Jam",             132)
    val TOAST_WITH_SWEETBERRY_JAM           = Item(133,  "Toast with Sweetberry Jam",           133)
    val TOAST_WITH_APPLE_JAM                = Item(134,  "Toast with Apple Jam",                134)
    val TOAST_WITH_BLACKBERRY_JAM           = Item(135,  "Toast with Blackberry Jam",           135)
    val TOAST_WITH_RASPBERRY_JAM            = Item(136,  "Toast with Raspberry Jam",            136)
    val TOAST_WITH_RAZZLEBERRY_JAM          = Item(137,  "Toast with Razzleberry Jam",          137)
    val TOAST_WITH_LEMON_JAM                = Item(138,  "Toast with Lemon Jam",                138)
    val TOAST_WITH_BLUEBERRY_JAM            = Item(139,  "Toast with Blueberry Jam",            139)
    val BAGEL                               = Item(140,  "Bagel",                               140)
    val BAGEL_WITH_CREAM_CHEESE             = Item(141,  "Bagel with Cream Cheese",             141)
    val BAGEL_WITH_PUMPKIN_CREAM_CHEESE     = Item(142,  "Bagel with Pumpkin Cream Cheese",     142)
    val BAGEL_WITH_STRAWBERRY_CREAM_CHEESE  = Item(143,  "Bagel with Strawberry Cream Cheese",  143)
    val BAGEL_WITH_BLUEBERRY_CREAM_CHEESE   = Item(144,  "Bagel with Blueberry Cream Cheese",   144)
    val BAGEL_WITH_SWEETBERRY_CREAM_CHEESE  = Item(145,  "Bagel with Sweetberry Cream Cheese",  145)
    val BAGEL_WITH_RAZZLEBERRY_CREAM_CHEESE = Item(146,  "Bagel with Razzleberry Cream Cheese", 146)
    val OLIVE                               = Item(147,  "Olive",                               147)
    val OLIVE_OIL                           = Item(148,  "Olive Oil",                           148)
    val LIGHTER                             = Item(149,  "Lighter",                             149)
    val BUCKET                              = Item(150,  "Bucket",                              150)
    val WATER_BUCKET                        = Item(151,  "Water Bucket",                        151)
    val LAVA_BUCKET                         = Item(152,  "Lava Bucket",                         152)
    val CHICKEN_EGG                         = Item(153,  "Chicken Egg",                         153)
    val DUCK_EGG                            = Item(154,  "Duck Egg",                            154)
    val FRIED_EGG                           = Item(155,  "Fried Egg",                           155)

    // ARMORS, WEAPONS, AND TOOLS

    val LEATHER                             = Item(156, "Leather", 156)
    val LEATHER_CAP                         = Item(157, "Leather Cap", 157)
    val LEATHER_SHIRT                       = Item(158, "Leather Shirt", 158)
    val LEATHER_JACKET                      = Item(159, "Leather Jacket", 159)
    val LEATHER_TROUSERS                    = Item(160, "Leather Trousers", 160)
    val LEATHER_SHOES                       = Item(161, "Leather Shoes", 161)
    val LEATHER_GLOVES                      = Item(162, "Leather Gloves", 162)
    val WOODEN_DAGGER                       = Item(163, "Wooden Dagger", 163)
    val WOODEN_SWORD                        = Item(164, "Wooden Sword", 164)
    val WOODEN_LONGSWORD                    = Item(165, "Wooden Longsword", 165)
    val WOODEN_GREATSWORD                   = Item(166, "Wooden Greatsword", 166)
    val WOODEN_AXE                          = Item(167, "Wooden Axe", 167)
    val WOODEN_BATTLEAXE                    = Item(168, "Wooden Battleaxe", 168)
    val WOODEN_PICKAXE                      = Item(169, "Wooden Pickaxe", 169)
    val WOODEN_ICEPICK                      = Item(170, "Wooden Icepick", 170)
    val WOODEN_SPADE                        = Item(171, "Wooden Spade", 171)
    val WOODEN_SPEAR                        = Item(172, "Wooden Spear", 172)
    val WOODEN_HOE                          = Item(173, "Wooden Hoe", 173)
    val WOODEN_SCYTHE                       = Item(174, "Wooden Scythe", 174)

    val COPPER_HELMET                       = Item(175, "Copper Helmet", 175)
    val COPPER_CHAINMAIL                    = Item(176, "Copper Chainmail", 176)
    val COPPER_BREASTPLATE                  = Item(177, "Copper Breastplate", 177)
    val COPPER_GAUNTLETS                    = Item(178, "Copper Gauntlets", 178)
    val COPPER_GRIEVES                      = Item(179, "Copper Grieves", 179)
    val COPPER_BOOTS                        = Item(180, "Copper Boots", 180)
    val COPPER_DAGGER                       = Item(181, "Copper Dagger", 181)
    val COPPER_SWORD                        = Item(182, "Copper Sword", 182)
    val COPPER_LONGSWORD                    = Item(183, "Copper Longsword", 183)
    val COPPER_GREATSWORD                   = Item(184, "Copper Greatsword", 184)
    val COPPER_AXE                          = Item(185, "Copper Axe", 185)
    val COPPER_BATTLEAXE                    = Item(186, "Copper Battleaxe", 186)
    val COPPER_PICKAXE                      = Item(187, "Copper Pickaxe", 187)
    val COPPER_ICEPICK                      = Item(188, "Copper Icepick", 188)
    val COPPER_SPADE                        = Item(189, "Copper Spade", 189)
    val COPPER_SPEAR                        = Item(190, "Copper Spear", 190)
    val COPPER_HOE                          = Item(191, "Copper Hoe", 191)
    val COPPER_SCYTHE                       = Item(192, "Copper Scythe", 192)

    val TIN_HELMET                          = Item(193, "Tin Helmet", 193)
    val TIN_CHAINMAIL                       = Item(194, "Tin Chainmail", 194)
    val TIN_BREASTPLATE                     = Item(195, "Tin Breastplate", 195)
    val TIN_GAUNTLETS                       = Item(196, "Tin Gauntlets", 196)
    val TIN_GRIEVES                         = Item(197, "Tin Grieves", 197)
    val TIN_BOOTS                           = Item(198, "Tin Boots", 198)
    val TIN_DAGGER                          = Item(199, "Tin Dagger", 199)
    val TIN_SWORD                           = Item(200, "Tin Sword", 200)
    val TIN_LONGSWORD                       = Item(201, "Tin Longsword", 201)
    val TIN_GREATSWORD                      = Item(202, "Tin Greatsword", 202)
    val TIN_AXE                             = Item(203, "Tin Axe", 203)
    val TIN_BATTLEAXE                       = Item(204, "Tin Battleaxe", 204)
    val TIN_PICKAXE                         = Item(205, "Tin Pickaxe", 205)
    val TIN_ICEPICK                         = Item(206, "Tin Icepick", 206)
    val TIN_SPADE                           = Item(207, "Tin Spade", 207)
    val TIN_SPEAR                           = Item(208, "Tin Spear", 208)
    val TIN_HOE                             = Item(209, "Tin Hoe", 209)
    val TIN_SCYTHE                          = Item(210, "Tin Scythe", 210)

    val SILVER_HELMET                       = Item(211, "Silver Helmet", 211)
    val SILVER_CHAINMAIL                    = Item(212, "Silver Chainmail", 212)
    val SILVER_BREASTPLATE                  = Item(213, "Silver Breastplate", 213)
    val SILVER_GAUNTLETS                    = Item(214, "Silver Gauntlets", 214)
    val SILVER_GRIEVES                      = Item(215, "Silver Grieves", 215)
    val SILVER_BOOTS                        = Item(216, "Silver Boots", 216)
    val SILVER_DAGGER                       = Item(217, "Silver Dagger", 217)
    val SILVER_SWORD                        = Item(218, "Silver Sword", 218)
    val SILVER_LONGSWORD                    = Item(219, "Silver Longsword", 219)
    val SILVER_GREATSWORD                   = Item(220, "Silver Greatsword", 220)
    val SILVER_AXE                          = Item(221, "Silver Axe", 221)
    val SILVER_BATTLEAXE                    = Item(222, "Silver Battleaxe", 222)
    val SILVER_PICKAXE                      = Item(223, "Silver Pickaxe", 223)
    val SILVER_ICEPICK                      = Item(224, "Silver Icepick", 224)
    val SILVER_SPADE                        = Item(225, "Silver Spade", 225)
    val SILVER_SPEAR                        = Item(226, "Silver Spear", 226)
    val SILVER_HOE                          = Item(227, "Silver Hoe", 227)
    val SILVER_SCYTHE                       = Item(228, "Silver Scythe", 228)

    val GOLD_HELMET                         = Item(229, "Gold Helmet", 229)
    val GOLD_CHAINMAIL                      = Item(230, "Gold Chainmail", 230)
    val GOLD_BREASTPLATE                    = Item(231, "Gold Breastplate", 231)
    val GOLD_GAUNTLETS                      = Item(232, "Gold Gauntlets", 232)
    val GOLD_GRIEVES                        = Item(233, "Gold Grieves", 233)
    val GOLD_BOOTS                          = Item(234, "Gold Boots", 234)
    val GOLD_DAGGER                         = Item(235, "Gold Dagger", 235)
    val GOLD_SWORD                          = Item(236, "Gold Sword", 236)
    val GOLD_LONGSWORD                      = Item(237, "Gold Longsword", 237)
    val GOLD_GREATSWORD                     = Item(238, "Gold Greatsword", 238)
    val GOLD_AXE                            = Item(239, "Gold Axe", 239)
    val GOLD_BATTLEAXE                      = Item(240, "Gold Battleaxe", 240)
    val GOLD_PICKAXE                        = Item(241, "Gold Pickaxe", 241)
    val GOLD_ICEPICK                        = Item(242, "Gold Icepick", 242)
    val GOLD_SPADE                          = Item(243, "Gold Spade", 243)
    val GOLD_SPEAR                          = Item(244, "Gold Spear", 244)
    val GOLD_HOE                            = Item(245, "Gold Hoe", 245)
    val GOLD_SCYTHE                         = Item(246, "Gold Scythe", 246)

    val COBOLT_HELMET                       = Item(247, "Cobolt Helmet", 247)
    val COBOLT_CHAINMAIL                    = Item(248, "Cobolt Chainmail", 248)
    val COBOLT_BREASTPLATE                  = Item(249, "Cobolt Breastplate", 249)
    val COBOLT_GAUNTLETS                    = Item(250, "Cobolt Gauntlets", 250)
    val COBOLT_GRIEVES                      = Item(251, "Cobolt Grieves", 251)
    val COBOLT_BOOTS                        = Item(252, "Cobolt Boots", 252)
    val COBOLT_DAGGER                       = Item(253, "Cobolt Dagger", 253)
    val COBOLT_SWORD                        = Item(254, "Cobolt Sword", 254)
    val COBOLT_LONGSWORD                    = Item(255, "Cobolt Longsword", 255)
    val COBOLT_GREATSWORD                   = Item(256, "Cobolt Greatsword", 256)
    val COBOLT_AXE                          = Item(257, "Cobolt Axe", 257)
    val COBOLT_BATTLEAXE                    = Item(258, "Cobolt Battleaxe", 258)
    val COBOLT_PICKAXE                      = Item(259, "Cobolt Pickaxe", 259)
    val COBOLT_ICEPICK                      = Item(260, "Cobolt Icepick", 260)
    val COBOLT_SPADE                        = Item(261, "Cobolt Spade", 261)
    val COBOLT_SPEAR                        = Item(262, "Cobolt Spear", 262)
    val COBOLT_HOE                          = Item(263, "Cobolt Hoe", 263)
    val COBOLT_SCYTHE                       = Item(264, "Cobolt Scythe", 264)

    val LITHIUM_HELMET                      = Item(265, "Lithium Helmet", 265)
    val LITHIUM_CHAINMAIL                   = Item(266, "Lithium Chainmail", 266)
    val LITHIUM_BREASTPLATE                 = Item(267, "Lithium Breastplate", 267)
    val LITHIUM_GAUNTLETS                   = Item(268, "Lithium Gauntlets", 268)
    val LITHIUM_GRIEVES                     = Item(269, "Lithium Grieves", 269)
    val LITHIUM_BOOTS                       = Item(270, "Lithium Boots", 270)
    val LITHIUM_DAGGER                      = Item(271, "Lithium Dagger", 271)
    val LITHIUM_SWORD                       = Item(272, "Lithium Sword", 272)
    val LITHIUM_LONGSWORD                   = Item(273, "Lithium Longsword", 273)
    val LITHIUM_GREATSWORD                  = Item(274, "Lithium Greatsword", 274)
    val LITHIUM_AXE                         = Item(275, "Lithium Axe", 275)
    val LITHIUM_BATTLEAXE                   = Item(276, "Lithium Battleaxe", 276)
    val LITHIUM_PICKAXE                     = Item(277, "Lithium Pickaxe", 277)
    val LITHIUM_ICEPICK                     = Item(278, "Lithium Icepick", 278)
    val LITHIUM_SPADE                       = Item(279, "Lithium Spade", 279)
    val LITHIUM_SPEAR                       = Item(280, "Lithium Spear", 280)
    val LITHIUM_HOE                         = Item(281, "Lithium Hoe", 281)
    val LITHIUM_SCYTHE                      = Item(282, "Lithium Scythe", 282)

    val IRON_HELMET                         = Item(283, "Iron Helmet", 283)
    val IRON_CHAINMAIL                      = Item(284, "Iron Chainmail", 284)
    val IRON_BREASTPLATE                    = Item(285, "Iron Breastplate", 285)
    val IRON_GAUNTLETS                      = Item(286, "Iron Gauntlets", 286)
    val IRON_GRIEVES                        = Item(287, "Iron Grieves", 287)
    val IRON_BOOTS                          = Item(288, "Iron Boots", 288)
    val IRON_DAGGER                         = Item(289, "Iron Dagger", 289)
    val IRON_SWORD                          = Item(290, "Iron Sword", 290)
    val IRON_LONGSWORD                      = Item(291, "Iron Longsword", 291)
    val IRON_GREATSWORD                     = Item(292, "Iron Greatsword", 292)
    val IRON_AXE                            = Item(293, "Iron Axe", 293)
    val IRON_BATTLEAXE                      = Item(294, "Iron Battleaxe", 294)
    val IRON_PICKAXE                        = Item(295, "Iron Pickaxe", 295)
    val IRON_ICEPICK                        = Item(296, "Iron Icepick", 296)
    val IRON_SPADE                          = Item(297, "Iron Spade", 297)
    val IRON_SPEAR                          = Item(298, "Iron Spear", 298)
    val IRON_HOE                            = Item(299, "Iron Hoe", 299)
    val IRON_SCYTHE                         = Item(300, "Iron Scythe", 300)

    val STEEL_HELMET                        = Item(301, "Steel Helmet", 301)
    val STEEL_CHAINMAIL                     = Item(302, "Steel Chainmail", 302)
    val STEEL_BREASTPLATE                   = Item(303, "Steel Breastplate", 303)
    val STEEL_GAUNTLETS                     = Item(304, "Steel Gauntlets", 304)
    val STEEL_GRIEVES                       = Item(305, "Steel Grieves", 305)
    val STEEL_BOOTS                         = Item(306, "Steel Boots", 306)
    val STEEL_DAGGER                        = Item(307, "Steel Dagger", 307)
    val STEEL_SWORD                         = Item(308, "Steel Sword", 308)
    val STEEL_LONGSWORD                     = Item(309, "Steel Longsword", 309)
    val STEEL_GREATSWORD                    = Item(310, "Steel Greatsword", 310)
    val STEEL_AXE                           = Item(311, "Steel Axe", 311)
    val STEEL_BATTLEAXE                     = Item(312, "Steel Battleaxe", 312)
    val STEEL_PICKAXE                       = Item(313, "Steel Pickaxe", 313)
    val STEEL_ICEPICK                       = Item(314, "Steel Icepick", 314)
    val STEEL_SPADE                         = Item(315, "Steel Spade", 315)
    val STEEL_SPEAR                         = Item(316, "Steel Spear", 316)
    val STEEL_HOE                           = Item(317, "Steel Hoe", 317)
    val STEEL_SCYTHE                        = Item(318, "Steel Scythe", 318)

    val BLUE_STEEL_HELMET                   = Item(319, "Blue Steel Helmet", 319)
    val BLUE_STEEL_CHAINMAIL                = Item(320, "Blue Steel Chainmail", 320)
    val BLUE_STEEL_BREASTPLATE              = Item(321, "Blue Steel Breastplate", 321)
    val BLUE_STEEL_GAUNTLETS                = Item(322, "Blue Steel Gauntlets", 322)
    val BLUE_STEEL_GRIEVES                  = Item(323, "Blue Steel Grieves", 323)
    val BLUE_STEEL_BOOTS                    = Item(324, "Blue Steel Boots", 324)
    val BLUE_STEEL_DAGGER                   = Item(325, "Blue Steel Dagger", 325)
    val BLUE_STEEL_SWORD                    = Item(326, "Blue Steel Sword", 326)
    val BLUE_STEEL_LONGSWORD                = Item(327, "Blue Steel Longsword", 327)
    val BLUE_STEEL_GREATSWORD               = Item(328, "Blue Steel Greatsword", 328)
    val BLUE_STEEL_AXE                      = Item(329, "Blue Steel Axe", 329)
    val BLUE_STEEL_BATTLEAXE                = Item(330, "Blue Steel Battleaxe", 330)
    val BLUE_STEEL_PICKAXE                  = Item(331, "Blue Steel Pickaxe", 331)
    val BLUE_STEEL_ICEPICK                  = Item(332, "Blue Steel Icepick", 332)
    val BLUE_STEEL_SPADE                    = Item(333, "Blue Steel Spade", 333)
    val BLUE_STEEL_SPEAR                    = Item(334, "Blue Steel Spear", 334)
    val BLUE_STEEL_HOE                      = Item(335, "Blue Steel Hoe", 335)
    val BLUE_STEEL_SCYTHE                   = Item(336, "Blue Steel Scythe", 336)

    val PLATINUM_HELMET                     = Item(337, "Platinum Helmet", 337)
    val PLATINUM_CHAINMAIL                  = Item(338, "Platinum Chainmail", 338)
    val PLATINUM_BREASTPLATE                = Item(339, "Platinum Breastplate", 339)
    val PLATINUM_GAUNTLETS                  = Item(340, "Platinum Gauntlets", 340)
    val PLATINUM_GRIEVES                    = Item(341, "Platinum Grieves", 341)
    val PLATINUM_BOOTS                      = Item(342, "Platinum Boots", 342)
    val PLATINUM_DAGGER                     = Item(343, "Platinum Dagger", 343)
    val PLATINUM_SWORD                      = Item(344, "Platinum Sword", 344)
    val PLATINUM_LONGSWORD                  = Item(345, "Platinum Longsword", 345)
    val PLATINUM_GREATSWORD                 = Item(346, "Platinum Greatsword", 346)
    val PLATINUM_AXE                        = Item(347, "Platinum Axe", 347)
    val PLATINUM_BATTLEAXE                  = Item(348, "Platinum Battleaxe", 348)
    val PLATINUM_PICKAXE                    = Item(349, "Platinum Pickaxe", 349)
    val PLATINUM_ICEPICK                    = Item(350, "Platinum Icepick", 350)
    val PLATINUM_SPADE                      = Item(351, "Platinum Spade", 351)
    val PLATINUM_SPEAR                      = Item(352, "Platinum Spear", 352)
    val PLATINUM_HOE                        = Item(353, "Platinum Hoe", 353)
    val PLATINUM_SCYTHE                     = Item(354, "Platinum Scythe", 354)

    val TITANIUM_HELMET                     = Item(355, "Titanium Helmet", 355)
    val TITANIUM_BREASTPLATE                = Item(356, "Titanium Chainmail", 356)
    val TITANIUM_CHAINMAIL                  = Item(357, "Titanium Breastplate", 357)
    val TITANIUM_GAUNTLETS                  = Item(358, "Titanium Gauntlets", 358)
    val TITANIUM_GRIEVES                    = Item(359, "Titanium Grieves", 359)
    val TITANIUM_BOOTS                      = Item(360, "Titanium Boots", 360)
    val TITANIUM_DAGGER                     = Item(361, "Titanium Dagger", 361)
    val TITANIUM_SWORD                      = Item(362, "Titanium Sword", 362)
    val TITANIUM_LONGSWORD                  = Item(363, "Titanium Longsword", 363)
    val TITANIUM_GREATSWORD                 = Item(364, "Titanium Greatsword", 364)
    val TITANIUM_AXE                        = Item(365, "Titanium Axe", 365)
    val TITANIUM_BATTLEAXE                  = Item(366, "Titanium Battleaxe", 366)
    val TITANIUM_PICKAXE                    = Item(367, "Titanium Pickaxe", 367)
    val TITANIUM_ICEPICK                    = Item(368, "Titanium Icepick", 368)
    val TITANIUM_SPADE                      = Item(369, "Titanium Spade", 369)
    val TITANIUM_SPEAR                      = Item(370, "Titanium Spear", 370)
    val TITANIUM_HOE                        = Item(371, "Titanium Hoe", 371)
    val TITANIUM_SCYTHE                     = Item(372, "Titanium Scythe", 372)

    val MALACHITE_HELMET                    = Item(373, "Malachite Helmet", 373)
    val MALACHITE_BREASTPLATE               = Item(374, "Malachite Chainmail", 374)
    val MALACHITE_CHAINMAIL                 = Item(375, "Malachite Breastplate", 375)
    val MALACHITE_GAUNTLETS                 = Item(376, "Malachite Gauntlets", 376)
    val MALACHITE_GRIEVES                   = Item(377, "Malachite Grieves", 377)
    val MALACHITE_BOOTS                     = Item(378, "Malachite Boots", 378)
    val MALACHITE_DAGGER                    = Item(379, "Malachite Dagger", 379)
    val MALACHITE_SWORD                     = Item(380, "Malachite Sword", 380)
    val MALACHITE_LONGSWORD                 = Item(381, "Malachite Longsword", 381)
    val MALACHITE_GREATSWORD                = Item(382, "Malachite Greatsword", 382)
    val MALACHITE_AXE                       = Item(383, "Malachite Axe", 383)
    val MALACHITE_BATTLEAXE                 = Item(384, "Malachite Battleaxe", 384)
    val MALACHITE_PICKAXE                   = Item(385, "Malachite Pickaxe", 385)
    val MALACHITE_ICEPICK                   = Item(386, "Malachite Icepick", 386)
    val MALACHITE_SPADE                     = Item(387, "Malachite Spade", 387)
    val MALACHITE_SPEAR                     = Item(388, "Malachite Spear", 388)
    val MALACHITE_HOE                       = Item(389, "Malachite Hoe", 389)
    val MALACHITE_SCYTHE                    = Item(390, "Malachite Scythe", 390)
}